/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import DTO.Archivo;
import DTO.DiscoDuro;
import DTO.StorageDevice;
import Metodos.TextPrompt;
import Repositorio.RepoArchivo;
import Repositorio.RepoPC;
import Repositorio.RepoStorageDivice;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jostin
 */
public class ArchivosView extends javax.swing.JFrame {

    TextPrompt tp;
    RepoStorageDivice RSD = RepoStorageDivice.getInstance();
    RepoArchivo RA = RepoArchivo.getInstance();
    RepoPC RPD = RepoPC.getInstance();

    /**
     * Creates new form AchivosView
     */
    public ArchivosView() {
        initComponents();
        this.setLocationRelativeTo(this);
        tp = new TextPrompt("Nombre del Archivo", nameFile);
        tp = new TextPrompt("Peso del archivo (MB)", sizeFile);
        this.nameFile.setEditable(false);
        this.sizeFile.setEditable(false);
        nameFile.setEnabled(false);
        sizeFile.setEnabled(false);
        addArchivo.setEnabled(false);
        mostrar();
    }

    public StorageDevice obtenerStorageEscogido() {
        if (ssdRB.isSelected()) {

        } else {
        }
        return new DiscoDuro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UnidadesAlmacenamiento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TArchivos = new javax.swing.JTable();
        addArchivo = new javax.swing.JButton();
        elimiarArchivo = new javax.swing.JButton();
        nameFile = new javax.swing.JTextField();
        sizeFile = new javax.swing.JTextField();
        ssdRB = new javax.swing.JRadioButton();
        discoRB = new javax.swing.JRadioButton();
        cargaArchivo = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Archivos en el sistema");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        TArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Peso", "Zona de alojamiento"
            }
        ));
        jScrollPane1.setViewportView(TArchivos);

        addArchivo.setBackground(new java.awt.Color(0, 153, 102));
        addArchivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addArchivo.setForeground(new java.awt.Color(255, 255, 255));
        addArchivo.setText("Agregar");
        addArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArchivoActionPerformed(evt);
            }
        });

        elimiarArchivo.setBackground(new java.awt.Color(255, 0, 0));
        elimiarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        elimiarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        elimiarArchivo.setText("Eliminar");

        sizeFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sizeFileKeyTyped(evt);
            }
        });

        UnidadesAlmacenamiento.add(ssdRB);
        ssdRB.setText("SSD");
        ssdRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssdRBActionPerformed(evt);
            }
        });

        UnidadesAlmacenamiento.add(discoRB);
        discoRB.setText("Disco Duro");
        discoRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ssdRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(discoRB))
                            .addComponent(sizeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cargaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(addArchivo)
                            .addGap(253, 253, 253)
                            .addComponent(elimiarArchivo))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssdRB)
                            .addComponent(discoRB))
                        .addGap(42, 42, 42)
                        .addComponent(nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sizeFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cargaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addArchivo)
                    .addComponent(elimiarArchivo))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void sizeFileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeFileKeyTyped
        char validar = evt.getKeyChar();

        if (validar < '0' || validar > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_sizeFileKeyTyped

    private void ssdRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssdRBActionPerformed
        this.nameFile.setEditable(true);
        this.sizeFile.setEditable(true);
        nameFile.setEnabled(true);
        sizeFile.setEnabled(true);
        addArchivo.setEnabled(true);
    }//GEN-LAST:event_ssdRBActionPerformed

    private void discoRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoRBActionPerformed
        this.nameFile.setEditable(true);
        this.sizeFile.setEditable(true);
        nameFile.setEnabled(true);
        sizeFile.setEnabled(true);
        addArchivo.setEnabled(true);
    }//GEN-LAST:event_discoRBActionPerformed

    private void addArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArchivoActionPerformed
        double pesoArchivo = Double.parseDouble(this.sizeFile.getText());
        Archivo archivo = new Archivo();
        archivo.setNombre(this.nameFile.getText());
        archivo.setTamaño(pesoArchivo / 1024);
        if (this.RPD.isPower()) {
            if (this.ssdRB.isSelected()) {
                RA.agregarArchivoSSD(archivo, cargaArchivo);
            } else if (this.discoRB.isSelected()) {
                RA.agregarArchivoDiscoDuro(archivo, cargaArchivo);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione donde se guardara el archivo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se puede realizar operacion,\nEncienda el computador");
        }
// Añadir un retraso de 1 segundo antes de actualizar la vista
        Timer timer = new Timer(1000, e -> mostrar());
        timer.setRepeats(false); // No repetir el timer
        timer.start();
    }//GEN-LAST:event_addArchivoActionPerformed

    public void extaerArchivo() {
        addArchivo.setEnabled(false);
        if (this.TArchivos.getSelectedRow() != -1) {
            this.nameFile.setText("");
            this.sizeFile.setText("");
        }
    }

    public final void mostrar() {
        DefaultTableModel modelo = (DefaultTableModel) this.TArchivos.getModel();
        modelo.setRowCount(0); // Limpiar todas las filas existentes en la tabla

        var archivosGuardados = this.RSD.getStoragedevice();

        for (StorageDevice device : archivosGuardados) {
            List<Archivo> archivos = device.getArchivos();
            if (archivos == null) {
                archivos = new ArrayList<>(); // Inicializa la lista si es null
            }

            for (Archivo archivo : archivos) {
                Object[] rowData = {
                    archivo.getNombre(),
                    archivo.getTamaño() * 1024 + "MG", // Convertir tamaño a MG
                    device.getTipo()
                };
                modelo.addRow(rowData); // Agregar una nueva fila al modelo
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchivosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchivosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TArchivos;
    private javax.swing.ButtonGroup UnidadesAlmacenamiento;
    private javax.swing.JButton addArchivo;
    private javax.swing.JProgressBar cargaArchivo;
    private javax.swing.JRadioButton discoRB;
    private javax.swing.JButton elimiarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameFile;
    private javax.swing.JTextField sizeFile;
    private javax.swing.JRadioButton ssdRB;
    // End of variables declaration//GEN-END:variables
}
