/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import DTO.PC;
import Repositorio.RepoPC;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Jostin
 */
public class Home extends javax.swing.JFrame {

    RepoPC RPC = RepoPC.getInstance();
    private DetailsBoard DB;
    private CreatePC CPC;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setTitle("Computer Simulator");
        this.setLocationRelativeTo(this);
        setImage(imageLabel, "C:\\Users\\Jostin\\OneDrive\\Documentos\\Jostin\\PracticasJava\\Examen3\\src\\Img\\componentes.jpg");
        this.apagerPc.setEnabled(false);
        validatePCCreate();
        isPCPower();
    }

    public void setDetailsBoard(DetailsBoard detailsBoard) {
        this.DB = detailsBoard;
    }

    public void setCreatePC(CreatePC createPC) {
        this.CPC = createPC;
    }

    public void validatePCCreate() {
        if (this.RPC.pcIsCreated() == true) {
            this.powerPC.setEnabled(true);
            this.crearPCBTN.setEnabled(false);
            this.remplazarComponente.setEnabled(true);
            this.addFile.setEnabled(true);
            this.RBoard.setText("Computador Creado y ensamblado");
            this.RBoard.setForeground(Color.ORANGE);
            this.verDetalle.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        crearPCBTN = new javax.swing.JButton();
        remplazarComponente = new javax.swing.JButton();
        powerPC = new javax.swing.JButton();
        apagerPc = new javax.swing.JButton();
        verDetalle = new javax.swing.JButton();
        RBoard = new javax.swing.JLabel();
        addFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        crearPCBTN.setBackground(new java.awt.Color(0, 153, 51));
        crearPCBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearPCBTN.setForeground(new java.awt.Color(255, 255, 255));
        crearPCBTN.setText("Crear computador");
        crearPCBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearPCBTNMouseClicked(evt);
            }
        });

        remplazarComponente.setBackground(new java.awt.Color(255, 255, 153));
        remplazarComponente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remplazarComponente.setText("Reemplazar Componente");
        remplazarComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remplazarComponenteActionPerformed(evt);
            }
        });

        powerPC.setBackground(new java.awt.Color(0, 153, 153));
        powerPC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        powerPC.setForeground(new java.awt.Color(255, 255, 255));
        powerPC.setText("Encender ");
        powerPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerPCActionPerformed(evt);
            }
        });

        apagerPc.setBackground(new java.awt.Color(255, 0, 0));
        apagerPc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apagerPc.setForeground(new java.awt.Color(255, 255, 255));
        apagerPc.setText("Apagar");
        apagerPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagerPcActionPerformed(evt);
            }
        });

        verDetalle.setBackground(new java.awt.Color(153, 255, 255));
        verDetalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        verDetalle.setText("Ver detalles ");
        verDetalle.setActionCommand("Ver detalles");
        verDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetalleActionPerformed(evt);
            }
        });

        RBoard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RBoard.setForeground(new java.awt.Color(0, 0, 255));
        RBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        addFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addFile.setText("Archivos en el sistema");
        addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Simulador de Computador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remplazarComponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearPCBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(powerPC)
                        .addGap(93, 93, 93)
                        .addComponent(apagerPc)
                        .addGap(189, 189, 189))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(crearPCBTN)
                        .addGap(26, 26, 26)
                        .addComponent(verDetalle)
                        .addGap(28, 28, 28)
                        .addComponent(remplazarComponente)
                        .addGap(41, 41, 41)
                        .addComponent(addFile)))
                .addGap(18, 18, 18)
                .addComponent(RBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apagerPc)
                    .addComponent(powerPC))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetalleActionPerformed
        DetailsBoard db = new DetailsBoard();
        db.SetHome(this);
        this.setVisible(false);
        db.setVisible(true);
    }//GEN-LAST:event_verDetalleActionPerformed

    private void crearPCBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearPCBTNMouseClicked
        if (this.RPC.pcIsCreated() == false || this.RPC.getComputador() == null) {
            CreatePC cpc = new CreatePC();
            cpc.setHome(this);
            this.setVisible(false);
            cpc.setVisible(true);
        }
    }//GEN-LAST:event_crearPCBTNMouseClicked

    private void powerPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerPCActionPerformed
        PC pc = new PC();
        setImage(imageLabel, "C:\\Users\\Jostin\\OneDrive\\Documentos\\Jostin\\PracticasJava\\Examen3\\src\\Img\\zonagamer.jpg");
        this.RPC.encender();
        isPCPower();

    }//GEN-LAST:event_powerPCActionPerformed

    private void addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileActionPerformed
        ArchivosView av = new ArchivosView();
        av.setVisible(true);
    }//GEN-LAST:event_addFileActionPerformed

    private void remplazarComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remplazarComponenteActionPerformed
        if (this.RPC.pcIsCreated() == true || this.RPC.getComputador() != null) {
            CreatePC cpc = new CreatePC();
            cpc.setHome(this);
            this.setVisible(false);
            cpc.setVisible(true);
        }
    }//GEN-LAST:event_remplazarComponenteActionPerformed

    private void apagerPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagerPcActionPerformed
        if (this.RPC.isPower()) {
            this.RPC.Apagar();
            isPCPower();
        }
    }//GEN-LAST:event_apagerPcActionPerformed

    public void isPCPower() {
        if (this.RPC.pcIsCreated() == true && !this.RPC.isPower()) {
            this.RBoard.setText("Computador creado, se encuentra en estado apagado");
            this.RBoard.setForeground(Color.RED);
        } else if (this.RPC.pcIsCreated() == true && this.RPC.isPower()) {
            this.RBoard.setText("Computador Encendido");
            this.RBoard.setForeground(Color.GREEN);
            this.powerPC.setEnabled(false);
            this.apagerPc.setEnabled(true);
        } else if (!this.RPC.pcIsCreated() == true) {
            this.powerPC.setEnabled(false);
            this.verDetalle.setEnabled(false);
            this.remplazarComponente.setEnabled(false);
            this.addFile.setEnabled(false);
            this.RBoard.setText("Agregue componentes para poder crear el PC");
            RBoard.setForeground(Color.BLACK);
            this.powerPC.setEnabled(false);
            this.apagerPc.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        }
        );
    }

    private void setImage(JLabel label, String route) {
        ImageIcon image = new ImageIcon(route);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RBoard;
    private javax.swing.JButton addFile;
    private javax.swing.JButton apagerPc;
    private javax.swing.JButton crearPCBTN;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton powerPC;
    private javax.swing.JButton remplazarComponente;
    private javax.swing.JButton verDetalle;
    // End of variables declaration//GEN-END:variables
}
